- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: joint_states
  gz_topic_name: /world/empty/model/iiwa7/joint_state
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# IMU
- ros_topic_name: "/iiwa7/sensors/imu/link_0"
  gz_topic_name: "/iiwa7/sensors/imu/link_0"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/iiwa7/sensors/imu/link_1"
  gz_topic_name: "/iiwa7/sensors/imu/link_1"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/iiwa7/sensors/imu/link_2"
  gz_topic_name: "/iiwa7/sensors/imu/link_2"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/iiwa7/sensors/imu/link_3"
  gz_topic_name: "/iiwa7/sensors/imu/link_3"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/iiwa7/sensors/imu/link_4"
  gz_topic_name: "/iiwa7/sensors/imu/link_4"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/iiwa7/sensors/imu/link_5"
  gz_topic_name: "/iiwa7/sensors/imu/link_5"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/iiwa7/sensors/imu/link_6"
  gz_topic_name: "/iiwa7/sensors/imu/link_6"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/iiwa7/sensors/imu/link_7"
  gz_topic_name: "/iiwa7/sensors/imu/link_7"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# Contacts
- ros_topic_name: "/iiwa7/sensors/contacts/link_0"
  gz_topic_name: "/iiwa7/sensors/contacts/link_0"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

- ros_topic_name: "/iiwa7/sensors/contacts/link_1"
  gz_topic_name: "/iiwa7/sensors/contacts/link_1"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

- ros_topic_name: "/iiwa7/sensors/contacts/link_2"
  gz_topic_name: "/iiwa7/sensors/contacts/link_2"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

- ros_topic_name: "/iiwa7/sensors/contacts/link_3"
  gz_topic_name: "/iiwa7/sensors/contacts/link_3"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

- ros_topic_name: "/iiwa7/sensors/contacts/link_4"
  gz_topic_name: "/iiwa7/sensors/contacts/link_4"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

- ros_topic_name: "/iiwa7/sensors/contacts/link_5"
  gz_topic_name: "/iiwa7/sensors/contacts/link_5"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

- ros_topic_name: "/iiwa7/sensors/contacts/link_6"
  gz_topic_name: "/iiwa7/sensors/contacts/link_6"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

- ros_topic_name: "/iiwa7/sensors/contacts/link_7"
  gz_topic_name: "/iiwa7/sensors/contacts/link_7"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS