services:
  camera_stream_container:
    build:
      context: .
      dockerfile: CameraStream.Dockerfile
    image: camera-stream-ros2
    container_name: camera-stream-container
    network_mode: host
    restart: unless-stopped
    runtime: nvidia
    
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_LAUNCH_BLOCKING=1
      - CAMERA_NAME=your_camera_name
    privileged: true
    devices:
      - "/dev/HID-SENSOR-2000e1.4.auto:/dev/HID-SENSOR-2000e1.4.auto"
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/video2:/dev/video2"
      - "/dev/video3:/dev/video3"
      - "/dev/video4:/dev/video4"
      - "/dev/video5:/dev/video5"
      # Параметры для L515 lidar
      # - "/dev/video5:/dev/video6"
      # - "/dev/video5:/dev/video7"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]