general_settings:
  robot_name: "LBRiiwa7R800"
  dataset_path: "./dataset"
  camera_list:
    # - "IntelCamera"
    - "D455_front"
    - "L515_lidar"
    - "D455_left"

robot_settings:
  robot_ip: 192.168.21.147
  robot_port: 30200
  recive_move_step: 50 # TODO: Не забудь убрать если сработает получение текущей позици
  virtual_threshold: 0.7 # Параметр, который можно будет удалить

  
camera_settings:
  width: 640
  height: 480
  fps: 30
  flip_horizontally: False
  flip_vertically: False
  nn_state: True
  
  export_setting:
    nn_model_name: yolo11s-pose
    convert_float16: True
    workspace: 0.512
    device: "0" # GPU (device=0), CPU (device=cpu), MPS for Apple silicon (device=mps), DLA for NVIDIA Jetson (device=dla:0 or device=dla:1)

calibration_settings:
  pattern_size: [6, 9]
  convolution_size: 3
  image_format_valid:
    - png
    - jpeg
    - jpg
  save_config:
    pattern_frames_path: ""
    config_name: "calibrationConfig"
    overwrite_pattern_frames: False
    save_calibration_info: True
